### ISSUE TITLE
Arduino Sketch

### ISSUE THREAD

**Issue by stylesuxx** [PaulMurrayCbr/ArdDrive#1]
Hey, very cool project.

I was just wondering, where I could find the Arduino Sketch?
Also maybe you could link the BT board you used - maybe this is obvious from the Sketch, but I just can not locate it.

Edit: Sorry, never mind it is there, right in the top level directory. Seems I was just blind....

**Comment by PaulMurrayCbr** [comment]
The bluetooth board is a freetronics HC-06 - the one with the headers. Pretty standard. The pairing code is 1234.
